language: python
python:
  - "3.6"
install:
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
script:
  - cd tests
  - tar -xzf "examples.tar"
  - pytest --cov=../src/
after_success:
  - coveralls
notifications:
  email: false